[package]
name = "dpim2025"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.34.0"
once_cell = "1.21.3"
rand = "0.9.2"
tempfile = "3.20.0"
scirs2-sparse = { git = "https://github.com/tiagomrns/scirs", package = "scirs2-sparse" }
num-integer = "0.1.46"
itertools = "0.14.0"
